/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-09-16 16:01:30 UTC)
 * on 2013-10-13 at 18:40:06 UTC 
 * Modify at your own risk.
 */

package com.appspot.connexus_apt.streamlist.model;

/**
 * Model definition for NearbyResult.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the streamlist. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class NearbyResult extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Media> mediaList;

  static {
    // hack to force ProGuard to consider Media used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(Media.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long myId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer queryLimit;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer queryOffset;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer resultSize;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double searchLatitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double searchLongitude;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Media> getMediaList() {
    return mediaList;
  }

  /**
   * @param mediaList mediaList or {@code null} for none
   */
  public NearbyResult setMediaList(java.util.List<Media> mediaList) {
    this.mediaList = mediaList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getMyId() {
    return myId;
  }

  /**
   * @param myId myId or {@code null} for none
   */
  public NearbyResult setMyId(java.lang.Long myId) {
    this.myId = myId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getQueryLimit() {
    return queryLimit;
  }

  /**
   * @param queryLimit queryLimit or {@code null} for none
   */
  public NearbyResult setQueryLimit(java.lang.Integer queryLimit) {
    this.queryLimit = queryLimit;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getQueryOffset() {
    return queryOffset;
  }

  /**
   * @param queryOffset queryOffset or {@code null} for none
   */
  public NearbyResult setQueryOffset(java.lang.Integer queryOffset) {
    this.queryOffset = queryOffset;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getResultSize() {
    return resultSize;
  }

  /**
   * @param resultSize resultSize or {@code null} for none
   */
  public NearbyResult setResultSize(java.lang.Integer resultSize) {
    this.resultSize = resultSize;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getSearchLatitude() {
    return searchLatitude;
  }

  /**
   * @param searchLatitude searchLatitude or {@code null} for none
   */
  public NearbyResult setSearchLatitude(java.lang.Double searchLatitude) {
    this.searchLatitude = searchLatitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getSearchLongitude() {
    return searchLongitude;
  }

  /**
   * @param searchLongitude searchLongitude or {@code null} for none
   */
  public NearbyResult setSearchLongitude(java.lang.Double searchLongitude) {
    this.searchLongitude = searchLongitude;
    return this;
  }

  @Override
  public NearbyResult set(String fieldName, Object value) {
    return (NearbyResult) super.set(fieldName, value);
  }

  @Override
  public NearbyResult clone() {
    return (NearbyResult) super.clone();
  }

}
