/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-09-16 16:01:30 UTC)
 * on 2013-10-08 at 01:40:14 UTC 
 * Modify at your own risk.
 */

package com.appspot.connexus_apt.streamlist.model;

/**
 * Model definition for Stream.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the streamlist. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Stream extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String coverURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime creationDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime lastNewMedia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer mediaLimit;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Media> mediaList;

  static {
    // hack to force ProGuard to consider Media used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(Media.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer mediaOffset;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long numberOfMedia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ownerEmail;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long ownerId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer queryIndex;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer queryLimit;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer queryOffset;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> tags;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long trendingViews;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long views;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCoverURL() {
    return coverURL;
  }

  /**
   * @param coverURL coverURL or {@code null} for none
   */
  public Stream setCoverURL(java.lang.String coverURL) {
    this.coverURL = coverURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getCreationDate() {
    return creationDate;
  }

  /**
   * @param creationDate creationDate or {@code null} for none
   */
  public Stream setCreationDate(com.google.api.client.util.DateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Stream setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getLastNewMedia() {
    return lastNewMedia;
  }

  /**
   * @param lastNewMedia lastNewMedia or {@code null} for none
   */
  public Stream setLastNewMedia(com.google.api.client.util.DateTime lastNewMedia) {
    this.lastNewMedia = lastNewMedia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMediaLimit() {
    return mediaLimit;
  }

  /**
   * @param mediaLimit mediaLimit or {@code null} for none
   */
  public Stream setMediaLimit(java.lang.Integer mediaLimit) {
    this.mediaLimit = mediaLimit;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Media> getMediaList() {
    return mediaList;
  }

  /**
   * @param mediaList mediaList or {@code null} for none
   */
  public Stream setMediaList(java.util.List<Media> mediaList) {
    this.mediaList = mediaList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMediaOffset() {
    return mediaOffset;
  }

  /**
   * @param mediaOffset mediaOffset or {@code null} for none
   */
  public Stream setMediaOffset(java.lang.Integer mediaOffset) {
    this.mediaOffset = mediaOffset;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Stream setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getNumberOfMedia() {
    return numberOfMedia;
  }

  /**
   * @param numberOfMedia numberOfMedia or {@code null} for none
   */
  public Stream setNumberOfMedia(java.lang.Long numberOfMedia) {
    this.numberOfMedia = numberOfMedia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOwnerEmail() {
    return ownerEmail;
  }

  /**
   * @param ownerEmail ownerEmail or {@code null} for none
   */
  public Stream setOwnerEmail(java.lang.String ownerEmail) {
    this.ownerEmail = ownerEmail;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getOwnerId() {
    return ownerId;
  }

  /**
   * @param ownerId ownerId or {@code null} for none
   */
  public Stream setOwnerId(java.lang.Long ownerId) {
    this.ownerId = ownerId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getQueryIndex() {
    return queryIndex;
  }

  /**
   * @param queryIndex queryIndex or {@code null} for none
   */
  public Stream setQueryIndex(java.lang.Integer queryIndex) {
    this.queryIndex = queryIndex;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getQueryLimit() {
    return queryLimit;
  }

  /**
   * @param queryLimit queryLimit or {@code null} for none
   */
  public Stream setQueryLimit(java.lang.Integer queryLimit) {
    this.queryLimit = queryLimit;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getQueryOffset() {
    return queryOffset;
  }

  /**
   * @param queryOffset queryOffset or {@code null} for none
   */
  public Stream setQueryOffset(java.lang.Integer queryOffset) {
    this.queryOffset = queryOffset;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getTags() {
    return tags;
  }

  /**
   * @param tags tags or {@code null} for none
   */
  public Stream setTags(java.util.List<java.lang.String> tags) {
    this.tags = tags;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTrendingViews() {
    return trendingViews;
  }

  /**
   * @param trendingViews trendingViews or {@code null} for none
   */
  public Stream setTrendingViews(java.lang.Long trendingViews) {
    this.trendingViews = trendingViews;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getViews() {
    return views;
  }

  /**
   * @param views views or {@code null} for none
   */
  public Stream setViews(java.lang.Long views) {
    this.views = views;
    return this;
  }

  @Override
  public Stream set(String fieldName, Object value) {
    return (Stream) super.set(fieldName, value);
  }

  @Override
  public Stream clone() {
    return (Stream) super.clone();
  }

}
